config/routes.rb
Devfinder::Application.routes.draw do
  root :to => 'posts#index'

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')

  get '/sign_in' => 'sessions#new'
  post '/sessions' => 'sessions#create', :as => 'sessions'
  get '/sign_out' => 'sessions#destroy'

  get '/locations/new', controller: 'locations', action: 'new', as: 'new_location'
  post '/locations', controller: 'locations', action: 'create'

  get '/locations', controller: 'locations', action: 'index', as: 'locations'
  get '/locations/:id', controller: 'locations', action: 'show', as: 'location'

  get '/locations/:id/edit', controller: 'locations', action: 'edit', as: 'edit_location'
  put '/locations/:id', controller: 'locations', action: 'update'

  delete '/locations/:id', controller: 'locations', action: 'destroy'

  get '/posts/new', controller: 'posts', action: 'new', as: 'new_post'
  post '/posts', controller: 'posts', action: 'create'

  get '/posts', controller: 'posts', action: 'index', as: 'posts'
  get '/posts/:id', controller: 'posts', action: 'show', as: 'post'

  get '/posts/:id/edit', controller: 'posts', action: 'edit', as: 'edit_post'
  put '/posts/:id', controller: 'posts', action: 'update'

  delete '/posts/:id', controller: 'posts', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'

  get '/users', controller: 'users', action: 'index', as: 'users'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  put '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :posts

  validate :name, :neighborhood, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :location

  validate :description, :presence => true
end

app/models/session.rb
class Session
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts

  validates :source_url, :name, :email, :presence => true

  def self.from_omniauth(auth)
    where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    create! do |user|
      user.access_token = auth.credentials.token
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = "#{auth.info.first_name} #{auth.info.last_name}"
      user.email = auth.info.email
      user.source_url = auth.info.avatar
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
  end

  def show
    @location = Location.find_by_id(params[:id])
  end

  def new
    @location = Location.new
    @user = User.find_by_id(session[:user_id])
  end

  def create
    @location = Location.new
    @location.name = params[:name]
    @location.neighborhood = params[:neighborhood]
    @location.street = params[:street]
    @location.city = params[:city]
    @location.state = params[:state]

    if @location.save
            redirect_to locations_url
          else
      render 'new'
    end
  end

  def edit
    @location = Location.find_by_id(params[:id])
  end

  def update
    @location = Location.find_by_id(params[:id])
    @location.name = params[:name]
    @location.neighborhood = params[:neighborhood]
    @location.street = params[:street]
    @location.city = params[:city]
    @location.state = params[:state]

    if @location.save
            redirect_to locations_url
          else
      render 'edit'
    end
  end

  def destroy
    @location = Location.find_by_id(params[:id])
    @location.destroy
        redirect_to locations_url
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
    @posts = @posts.sort_by(&:posted_time).reverse
    @users = User.all
    @users_leaderboard = @users.sort_by { |user| Post.where(:user_id => user.id).count}.reverse
  end

  def show
    @post = Post.find_by_id(params[:id])
  end

  def new
    @post = Post.new
    @statuses = ["Coding", "Hanging Out", "Lunch"]
    @durations = ["1:00","2:00","3:00","4:00","5:00","6:00","7:00","8:00","9:00","10:00","11:00","12:00"]
    @user = User.find_by_id(session[:user_id])
  end

  def create
    @post = Post.new
    @post.user_id = params[:user_id]
    @post.location_id = params[:location_id]
    @post.status = params[:status]
    @post.duration = params[:duration]
    @post.description = params[:description]
    @post.posted_time = params[:posted_time]

    if @post.save
            redirect_to posts_url
          else
      render 'new'
    end
  end

  def edit
    @post = Post.find_by_id(params[:id])
    @statuses = ["Coding", "Hanging Out", "Lunch"]
    @durations = ["1:00","2:00","3:00","4:00","5:00","6:00","7:00","8:00","9:00","10:00","11:00","12:00"]
    @user = User.find_by_id(session[:user_id])
  end

  def update
    @post = Post.find_by_id(params[:id])
    @post.user_id = params[:user_id]
    @post.location_id = params[:location_id]
    @post.status = params[:status]
    @post.duration = params[:duration]
    @post.description = params[:description]
    @post.posted_time = params[:posted_time]

    if @post.save
            redirect_to posts_url
          else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    @post.destroy
        redirect_to posts_url
      end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path, :notice => "Welcome, #{user.name}"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, :notice => "You successfully logged out. Thanks for visiting."
  end

  # def create

  #   if User.find_by_email(params[:email]).present?
  #     session[:email] = params[:email]
  #     redirect_to posts_url, :notice => "Sign-in successful!"
  #   else
  #     redirect_to new_session_url, :notice => "We were unable to find that email."
  #   end
  # end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.name = params[:name]
    @user.source_url = params[:source_url]
    @user.tsl_class = params[:tsl_class]
    @user.email = params[:email]
    @user.twitter = params[:twitter]

    if @user.save
            redirect_to users_url
          else
      render 'new'
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    @user.name = params[:name]
    @user.source_url = params[:source_url]
    @user.tsl_class = params[:tsl_class]
    @user.email = params[:email]
    @user.phone = params[:phone]
    @user.twitter = params[:twitter]

    if @user.save
            redirect_to users_url
          else
      render 'edit'
    end
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
        redirect_to users_url
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devfinder</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <a class="brand" href="/">DevFinder</a>
      <ul class="nav">
      <li class="<%= 'active' if current_page?(posts_url) || current_page?(root_url) %>"><a href="<%= posts_url %>">Board</a></li>
      <li class="<%= 'active' if current_page?(locations_url) %>"><a href="<%= locations_url %>">Locations</a></li>
      <li><a href="https://starterleague.campfirenow.com/room/419764">Campfire</a></li>

      </ul>
      <div id="navbar-right">
        <ul class="nav">
          <% if current_user %>
            <li><a href="/sign_out">Sign Out</a></li>
          <% else %>
            <li><a href="/sign_in">Sign In</a></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<div class="container">
 <% if notice.present? %>
  <div class="alert alert-success">
    <%= notice %>
  </div>
 <% end %>

<%= yield %>
</div>
</body>
</html>

app/views/locations/edit.html.erb
<h1>Editing Location #<%= @location.id %></h1>


<%= form_tag(location_url(@location), method: 'put') do %>

  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name, @location.name %>
  </div>

  <div>
    <%= label_tag :neighborhood %><br />
    <%= text_field_tag :neighborhood, @location.neighborhood %>
  </div>

  <div>
    <%= label_tag :street %><br />
    <%= text_field_tag :street, @location.street %>
  </div>

  <div>
    <%= label_tag :city %><br />
    <%= text_field_tag :city, @location.city %>
  </div>

  <div>
    <%= label_tag :state %><br />
    <%= text_field_tag :state, @location.state %>
  </div>

  
  <div>
    <%= submit_tag "Update Location" %>
  </div>

<% end %>

app/views/locations/index.html.erb
<h1>Locations</h1>

<p><%= link_to 'Add a New Location', new_location_url %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Neighborhood</th>
    </tr>
  </thead>

  <tbody>
  <% @locations.each do |location| %>
    <tr>
      <td><%= location.name %></td>
      <td><%= location.neighborhood %></td>

      <td><%= link_to 'Show', location_url(location) %></td>
      <td><%= link_to 'Edit', edit_location_url(location) %></td>
      <td><%= link_to 'Destroy', location_url(location), method: 'delete', data: { confirm: "Do you really want to delete this location?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/locations/new.html.erb
<h1 class="span8 offset2">Add your coding spot.</h1>


  <%= form_tag(locations_url, method: 'post', :class => 'clearfix form-horizontal span6 offset2') do %>

  <%= hidden_field_tag :user_id, @user.id %>

  <div class="control-group">
    <%= label_tag :name, "Name", :class => "control-label" %>
      <div class="controls">
      <%= text_field_tag :name %>
    </div>
  </div>

  <div class="control-group">
    <%= label_tag :neighborhood, "Neighborhood", :class => "control-label" %>
      <div class="controls">
      <%= text_field_tag :neighborhood %>
    </div>
  </div>

  <div>
    <button type="submit" class="btn btn-primary span2 offset2">Create Location</button>
  </div>
<% end %>

app/views/locations/show.html.erb
<h1>Location #<%= @location.id %></h1>

<p>
  <b>Name:</b>
  <%= @location.name %>
</p>

<p>
  <b>Neighborhood:</b>
  <%= @location.neighborhood %>
</p>

<p>
  <b>Street:</b>
  <%= @location.street %>
</p>

<p>
  <b>City:</b>
  <%= @location.city %>
</p>

<p>
  <b>State:</b>
  <%= @location.state %>
</p>

app/views/posts/edit.html.erb
<h1 class="span8 offset2">Edit your post below.</h1>


<%= form_tag(post_url(@post), method: 'put', :class => 'clearfix form-horizontal span6 offset2') do %>

  <%= hidden_field_tag :user_id, @post.user_id %>

  <div class="control-group">
    <%= label_tag :location_id, "Location", :class => "control-label" %>
      <div class="controls">
        <%= select_tag :location_id, options_from_collection_for_select(Location.all, :id, :name, @post.location_id) %> <br />
        <%= link_to 'Or add a new location', new_location_url %>
      </div>
  </div>

  <div class="control-group">
    <%= label_tag :status, "Status", :class => "control-label" %>
      <div class="controls">
      <%= select_tag :status, options_for_select(@statuses, @post.status) %>
      </div>
  </div>

  <div class="control-group">
    <%= label_tag :duration, "How long?", :class => "control-label" %>
      <div class="controls">
      <%= select_tag :duration, options_for_select(@durations, @post.duration) %>
    </div>
  </div>

  <div class="control-group">
    <%= label_tag :description, "Description", :class => "control-label" %>
      <div class="controls">
      <%= text_field_tag :description, @post.description %>
    </div>
  </div>

  <%= hidden_field_tag :posted_time, Time.new %>

    <div>
      <button type="submit" class="btn btn-primary span2 offset2">Update Post</button>
    </div>
<% end %>

app/views/posts/index.html.erb
<div class="left-col">
  <div class="button-header">
    <% if current_user %>
        <a href="<%= new_post_url %>"><button class="btn btn-primary btn-large span3 offset2">git add</button></a>
    <% else %>
      <a href="/auth/starterleague"><button class="btn btn-primary btn-large span3 offset2">Sign in via TSL Portal</button></a>
    <% end %>
  </div>

  <% @posts.each do |post| %>
    <div class="clearfix hero-unit">
      <div class="media">
        <a class="pull-left" href="<%= user_url(post.user.id) %>">
          <%= image_tag post.user.source_url, :class => "media-object img-circle" %>
        </a>
        <div class="media-body">
          <h4 class="media-heading"><%= post.user.name %> at <%= link_to post.location.name, location_url(post.location.id) %><span class="duration"> (Until <%= post.duration %>)</span></h4>
          <div class="media">
            <% if post.description.length >= 1 %>
              <p>"<%= post.description %>"</p>
            <% else %>
              <br />
            <% end %>
            <h5><%= distance_of_time_in_words(post.posted_time, to_time = Time.now, include_seconds = false) %> ago
            <%= link_to image_tag("iconmonstr-trash-can-15-icon.png", :class => 'edit-button right'), post_url(post.id), :method => 'delete', data: { confirm: "Do you really want to delete this post?" } %>
            <%= link_to image_tag("iconmonstr-edit-9-icon.png", :class => 'edit-button right'), edit_post_url(post.id) %>
            </h5>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="right-col">
  <h1>Leaderboard</h1>
  <% @users_leaderboard.each do |user| %>
    <div class="hero-unit">
      <div class="media">
        <a class="pull-left" href="<%= user_url(user.id) %>">
          <%= image_tag user.source_url, :class => "media-object img-circle" %>
        </a>
        <h4 class="media-header"><%= user.name %></h4>
          <div class="media-body">
             <p><%= user.posts.count %> coding sessions</p>
          </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1 class="span8 offset2">Tell us where you're coding.</h1>


<%= form_tag(posts_url, method: 'post', :class => 'clearfix form-horizontal span6 offset2') do %>

  <%= hidden_field_tag :user_id, @user.id %>

  <div class="control-group">
    <%= label_tag :location_id, "Location", :class => "control-label" %>
      <div class="controls">
        <%= select_tag :location_id, options_from_collection_for_select(Location.all, :id, :name) %> <br />
        <%= link_to 'Or add a new location', new_location_url %>
      </div>
  </div>

<!--   <div class="control-group">
    <%= label_tag :status, "Status", :class => "control-label" %>
      <div class="controls">
      <%= select_tag :status, options_for_select(@statuses) %>
      </div>
  </div> -->

  <div class="control-group">
    <%= label_tag :duration, "Until...", :class => "control-label" %>
      <div class="controls">
      <%= select_tag :duration, options_for_select(@durations) %>
    </div>
  </div>

  <div class="control-group">
    <%= label_tag :description, "Description", :class => "control-label" %>
      <div class="controls">
      <%= text_area_tag :description %>
    </div>
  </div>

  <%= hidden_field_tag :posted_time, Time.new %>

    <div>
      <button type="submit" class="btn btn-primary span2 offset2">Create Post</button>
    </div>
<% end %>

app/views/posts/show.html.erb
<h1>Post #<%= @post.id %></h1>

<p>
  <b>User:</b>
  <%= @post.user_id %>
</p>

<p>
  <b>Location:</b>
  <%= @post.location_id %>
</p>

<p>
  <b>Status:</b>
  <%= @post.status %>
</p>

<p>
  <b>Duration:</b>
  <%= @post.duration %>
</p>

<p>
  <b>Description:</b>
  <%= @post.description %>
</p>

app/views/users/edit.html.erb
<h1>Editing User #<%= @user.id %></h1>


<%= form_tag(user_url(@user), method: 'put') do %>

  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name, @user.name %>
  </div>

  <div>
    <%= label_tag :source_url %><br />
    <%= text_field_tag :source_url, @user.source_url %>
  </div>

  <div>
    <%= label_tag :tsl_class %><br />
    <%= text_field_tag :tsl_class, @user.tsl_class %>
  </div>

  <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email, @user.email %>
  </div>

  <div>
    <%= label_tag :phone %><br />
    <%= number_field_tag :phone, @user.phone %>
  </div>

  <div>
    <%= label_tag :twitter %><br />
    <%= text_field_tag :twitter, @user.twitter %>
  </div>

  
  <div>
    <%= submit_tag "Update User" %>
  </div>

<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<p><%= link_to 'Add a New User', new_user_url %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Picture</th>
      <th>Tsl class</th>
      <th>Email</th>
      <th>Twitter</th>
    </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= image_tag user.source_url %></td>
      <td><%= user.tsl_class %></td>
      <td><%= user.email %></td>
      <td><%= user.twitter %></td>

      <td><%= link_to 'Show', user_url(user) %></td>
      <td><%= link_to 'Edit', edit_user_url(user) %></td>
      <td><%= link_to 'Destroy', user_url(user), method: 'delete', data: { confirm: "Do you really want to delete this user?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>


<%= form_tag(users_url, method: 'post') do %>


  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name %>
  </div>

    <div>
    <%= label_tag :source_url %><br />
    <%= text_field_tag :source_url %>
  </div>

    <div>
    <%= label_tag :tsl_class %><br />
    <%= text_field_tag :tsl_class %>
  </div>

    <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>

<!--     <div>
    <%= label_tag :phone %><br />
    <%= number_field_tag :phone %>
  </div> -->

    <div>
    <%= label_tag :twitter %><br />
    <%= text_field_tag :twitter %>
  </div>


  <div>
    <%= submit_tag "Create User" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>User #<%= @user.id %></h1>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Source url:</b>
  <%= @user.source_url %>
</p>

<p>
  <b>Tsl class:</b>
  <%= @user.tsl_class %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @user.phone %>
</p>

<p>
  <b>Twitter:</b>
  <%= @user.twitter %>
</p>